# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_top/zynq_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top || ORIG_REF_NAME==zynq_top}]

# IP: bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_processing_system7_0_0 || ORIG_REF_NAME==zynq_top_processing_system7_0_0}]

# XDC: bd/zynq_top/zynq_top_ooc.xdc
