# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/thoyt/fpga_work/uzed_base_system/uzed_base_system.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xci
# IP: The module: 'zynq_top_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thoyt/fpga_work/uzed_base_system/uzed_base_system.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_top_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/thoyt/fpga_work/uzed_base_system/uzed_base_system.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xci
# IP: The module: 'zynq_top_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thoyt/fpga_work/uzed_base_system/uzed_base_system.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_top_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
